obj-m:=chardriver.o
KD=/lib/modules/$(shell uname -r)/build/
PWD:=$(shell pwd)

default:
	$(MAKE) -C $(KD) M=$(PWD) modules
	gcc -o chardriver_Application chardriver_Application.c
	
clean:
	$(MAKE) -C $(KD) M=$(PWD) clean
	rm chardriver_Application

install:
	$(MAKE) -C $(KD) M=$(PWD) modules_install