obj-m:=chardriver.o
KD=/lib/modules/$(shell uname -r)/build/
PWD:=$(shell pwd)

default:
	$(MAKE) -C $(KD) M=$(PWD) modules
	gcc -o Driver_Application dDriver_Application.c
	
clean:
	$(MAKE) -C $(KD) M=$(PWD) clean
	rm Driver_Application

install:
	$(MAKE) -C $(KD) M=$(PWD) modules_install